services:
  do:
    image: ubuntu:24.04
    container_name: do
    tty: true
    environment:
      - DISPLAY=host.docker.internal:0
    working_dir: /do
    volumes:
      - .:/do
      - /tmp/.X11-unix:/tmp/.X11-unix
